services:
  agriin:
    image: 'postgres:latest'
    container_name: database
    environment:
      - POSTGRES_DB=agriin
      - POSTGRES_PASSWORD=sidati@nouhi
      - POSTGRES_USER=postgres
      - PGDATA=/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - agriin

  agriin-cache:
    image: 'redis:latest'
    container_name: agriin-cache
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - agriin

  app:
    container_name: agriin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8084"
    depends_on:
      agriin:
        condition: service_healthy
      agriin-cache:
        condition: service_healthy
    restart: no
    networks:
      - agriin

networks:
  agriin:
    attachable: true
    name: agriin
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112

volumes:
  postgres-db:
    driver: local